emotions = {
    b'\xf0\x9f\x98\x84': 'happy',
    b'\xF0\x9F\x98\x81': 'happy',
    b'\xF0\x9F\x98\x82': 'happy',
    b'\xF0\x9F\x98\x80': 'happy',
    b'\xF0\x9F\x98\x8A': 'happy',
    b'\xF0\x9F\x98\x86': 'happy',
    b'\xf0\x9f\x98\x83': 'happy',
    b'\xf0\x9f\xa4\xa9': 'happy',
    b'\xf0\x9f\xa5\xb3': 'happy',
    b'\xF0\x9F\x98\x92': 'sad',
    b'\xF0\x9F\x98\x9E': 'sad',
    b'\xF0\x9F\x98\x94': 'sad',
    b'\xF0\x9F\x98\x9F': 'sad',
    b'\xF0\x9F\x98\x95': 'sad',
    b'\xe2\x98\xb9': 'sad',
    b'\xF0\x9F\x98\xAB': 'sad',
    b'\xF0\x9F\x98\xA9': 'sad',
    b'\xF0\x9F\x98\x93': 'sad',
    b'\xF0\x9F\x91\xBF': 'angry',
    b'\xF0\x9F\x98\xAC': 'angry',
    b'\xF0\x9F\x98\xA4': 'angry',
    b'\xF0\x9F\x98\xA1': 'angry',
    b'\xF0\x9F\x91\xBA': 'angry',
    b'\xF0\x9F\x92\x80': 'angry',
    b'\xF0\x9F\x98\xA0': 'angry',
    b'\xf0\x9f\xa4\xaf': 'angry',
    b'\xf0\x9f\xa4\xa8': 'angry'
}

response = {
    'happy greeting': 'Привет, я чувствую, что тебе очень радостно!',
    'sad greeting': 'Привет, не грусти!',
    'angry greeting': 'Привет, ого, сколько злости!',
    'not understood': 'Я тебя не понимаю!',
    'happy happy': 'Как здорово, что тебе все радостней и радостней!',
    'sad happy': 'Как хорошо, что тебе уже лучше!',
    'angry happy': 'Кажется, у тебя получилось успокоиться!',
    'happy sad': 'Зачем же расстраиваться, все же было хорошо.',
    'sad sad': 'Мне жаль, что ты все еще грустишь',
    'angry sad': 'Тебя что-то раздражало, а теперь тебе грустно!',
    'angry angry': 'Чувствую, ты все еще злишься.',
    'sad angry': 'Тебе было грустно, а сейчас тебя что-то раздражает!',
    'happy angry': 'Как же так! Тебе было так радостно, а сейчас тебя что-то раздражает.'
}